---
# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always
  
# tasks file for workstation
- block:
  ## User configs
  # Del defolt catalogs
  # Create my catalog structure
  # Copy dotfiles from files/users/sf
  - import_tasks: users/sf.yml 

## desktop environments
## now not need


  ## system setup
  - import_tasks: system_setup/scripts.yml
  - import_tasks: system_setup/utils.yml
  - import_tasks: system_setup/simlinks.yml

  ## install software
  - import_tasks: software/chromium.yml # TODO
  - import_tasks: software/firefox.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/spotify.yml
  - import_tasks: software/vlc.yml
  - import_tasks: software/mosh.yml
  - import_tasks: software/tmux.yml
  - import_tasks: software/tmuxinator.yml
  - import_tasks: software/mongodb.yml
  - import_tasks: software/postgresql.yml
  - import_tasks: software/kubectl.yml
  - import_tasks: software/slack.yml
  - import_tasks: software/nodejs.yml
  - import_tasks: software/yarn.yml
  - import_tasks: software/sublime_merge.yml
  - import_tasks: software/sublime_text.yml
  - import_tasks: software/postman.yml
  - import_tasks: software/intellij-idea-ultimate.yml
  - import_tasks: software/pycharm-professional.yml
  - import_tasks: software/telegram-desktop.yml
  - import_tasks: software/docker.yml
  - import_tasks: software/sdkman.yml

  rescue:
    - set_fact: task_failed=true