---
# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always
  
# tasks file for workstation
- block:
  ## User configs
  # create catalog structure and copy dotfiles
  - import_tasks: users/sf.yml #TODO

## desktop environments
## now not need


  ## system setup
  - import_tasks: system_setup/scripts.yml #TODO

  ## install software
  - import_tasks: software/chromium.yml # TODO
  - import_tasks: software/firefox.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/spotify.yml
  - import_tasks: software/vlc.yml

  rescue:
    - set_fact: task_failed=true