---
- name: software | sublime_text/sublime_text | download sublimetext's .deb file
  get_url: url={{ sublimetext_url_deb }} dest={{sublimetext_tmp_deb}}
  tags: ["packages","sublimetext"]

- name: software | sublime_text/sublime_text | install sublimetext for debian family os
  apt: deb={{sublimetext_tmp_deb}}
  tags: ["packages","sublimetext"]