---
- name: system_setup | Install usefull CLI own tools\n
        (rg, htop, xclip, rename, jpegoptim,\n
                 OptiPNG, jq, ffmpeg, tree,\n
         httpie, fortune, cowsay, yamllint, flameshot)
    apt:
      name:
          - ripgrep
          - xclip
          - rename
          - jpegoptim
          - optipng
          - jq
          - ffmpeg
          - tree
          - httpie
          - fortune
          - cowsay
          - htop
          - yamllint
          - trash-cli
          - nmap
          - traceroute
          - xprintidle
          # https://github.com/flameshot-org/flameshot/
          - flameshot

      state: latest


- name: system_setup | pygments
    pip:
      name: Pygments

# TODO setup shortkeys for flameshot
# - name: system_setup | set new shortcats for flameshot
#   ansible.builtin.shell: /usr/bin/flameshot gui 