---
- name: software | docker | prepare install package RedHat
  include_tasks: docker/setup-RedHat.yml
  when: 
    - docker is defined
    - docker == true
    - ansible_os_family == 'RedHat'

- name: software | docker | prepare install package Debian
  include_tasks: docker/setup-Debian.yml
  when: 
    - docker is defined
    - docker == true
    - ansible_os_family == 'Debian'

- name: software | docker | install package
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  when: 
    - docker is defined
    - docker == true
  notify: restart docker

- name: software | docker | ensure Ddcker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  when: 
    - docker is defined
    - docker == true

- name: software | docker | ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  when: 
    - docker is defined
    - docker == true

- name: software | docker | ensure docker users are added to the docker group
  include_tasks: docker/docker-users.yml
  when: 
    - docker is defined
    - docker == true
    - docker_users | length > 0