---
- name: software | firefox | install syncthing packages
  tags: firefox
  become_user: sf
  package:
    name:
      - firefox
    state: latest
  when:
    - firefox is defined
    - firefox == true