--- # установка
- name: software | sdkman | install scripts
  include_tasks: sdkman/install.yml
  when: 
    - sdkman is defined
    - sdkman == true

# установление переменных в файлы терминальных профайлов
- block:
    - name: software | sdkman | run sdkman scripts
      include_tasks: sdkman.yml

    - name: software | sdkman | install sdkman scripts in rc files
      include_tasks: sdkman/persist_env.yml
      loop:
        - .bash_profile
        - .profile
        - .bashrc
        - .zshrc
      loop_control:
        loop_var: sdkman_profile
  environment:
    SDKMAN_DIR: '{{ sdkman_dir }}'
    SDKMAN_OFFLINE_MODE: 'false'
  become: '{{ sdkman_user != ansible_user_id }}'
  become_user: '{{ sdkman_user }}'
  when: 
    - sdkman is defined
    - sdkman == true

# Обновление альтернатив сдк мэна
- name: software | sdkman | update alternatives (candidate's)
  alternatives:
    name: "{{ item.name }}"
    path: "{{ sdkman_dir }}/candidates/{{ item.candidate }}/current/bin/{{ item.name }}"
    link: "{{ item.link }}"
  loop: "{{ sdkman_update_alternatives }}"
  become: yes
  when: 
    - sdkman is defined
    - sdkman == true
    - ansible_os_family != 'Darwin'
  tags:
    - sdkman_privilege