---
- name: software | spotify | install package
  tags: packages,snap,spotify,workstation-packages
  become_user: sf
  snap:
    name: spotify
    state: present
  when:
    - spotify is defined
    - spotify == true