---
- name: software | vlc | install package
  tags: packages,snap,vlc,workstation-packages
  become_user: sf
  snap:
    name: vlc
    state: present
    classic: yes
  when:
    - vlc is defined
    - vlc == true