---
# vars file for workstation
path_for_scripts: /home/sf/skripts
path_for_dotfiles: /home/sf/.dotfiles

user_workstation: sf

# ~~~~~~SDKman vars~~~~~~

# Default user/group owner of the SDKMAN directory is determined by
# `ansible_user_id' and `ansible_user_gid', respectively.
# They can be overidden with the following variables.
sdkman_user: sf
sdkman_group: sf
# The directory in which to download the SDKMAN initialization script.
sdkman_tmp_dir: /tmp
# Validate SSL when downloading init script?
# This is different from `sdkman_insecure_ssl' (see below).
sdkman_validate_ssl: true

# vars file for ansible-sdkman
system_packages: []

# ~~~~~~Docker vars~~~~~~

# A list of users who will be added to the docker group.
docker_users: []

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Used only for Debian/Ubuntu. Switch 'stable' to 'nightly' if needed.
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

# Used only for RedHat/CentOS/Fedora.
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_nightly: '0'
docker_yum_repo_enable_test: '0'
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg

