---
# handlers file for workstation

# handlers file for ansible-sdkman

- name: Cleanup sdkman script
  file:
    path: '{{ sdkman_tmp_dir }}/sdkman_script'
    state: absent

# handler for restart docker daemon if the docker package is updated
- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"