---
# tasks file for base
# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/roman.yml
  - import_tasks: users/root.yml

  # install software
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_utilities.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/openssh.yml
  - import_tasks: system_setup/scripts.yml

  rescue:
    - set_fact: task_failed=true
